# action.yml
name: 'Sun-CI'
description: 'Sun Asterisk Code Quality'
inputs:
  path:
   description: 'Path running check phpcs'
   required: true
   default: 'app'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
      - ${{ inputs.path }}
icon: 'check-square'
color: 'red'
